aws:
  s3:
    bucket-name: logs-apne2
  kinesis:
    stream-name: logs-apne2
    application-name: transmitter
    endpoint: kinesis.ap-northeast-2.amazonaws.com
    idle-time-between-reads-in-millis: 1000
    region-id: ap-northeast-2

# h2 database
spring:
  config:
    import:
      - classpath:/application-secret.yml
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

transmitter:
  queue:
    max-bytes: 8000000
    max-records: 6000
server:
  port: 8081